// <auto-generated />
namespace BlogMVCApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CommentUpdated_UserImage_ArticleId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentUpdated_UserImage_ArticleId));
        
        string IMigrationMetadata.Id
        {
            get { return "202103121740438_CommentUpdated_UserImage_ArticleId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
